# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/lnsqr/Documents/GitHub/CPU_LAB/I7_6700K_vol1.0/I7_6700K_vol1.0/I7_6700K_vol1.0.cache/wt [current_project]
set_property parent.project_path C:/Users/lnsqr/Documents/GitHub/CPU_LAB/I7_6700K_vol1.0/I7_6700K_vol1.0/I7_6700K_vol1.0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/lnsqr/Documents/GitHub/CPU_LAB/Lab5课程设计/1.单周期FPGA/extender.v
  C:/Users/lnsqr/Documents/GitHub/CPU_LAB/Lab5课程设计/1.单周期FPGA/cpu_choose.v
  C:/Users/lnsqr/Documents/GitHub/CPU_LAB/Lab5课程设计/1.单周期FPGA/is.v
  C:/Users/lnsqr/Documents/GitHub/CPU_LAB/Lab5课程设计/1.单周期FPGA/change_type.v
  C:/Users/lnsqr/Documents/GitHub/CPU_LAB/Lab5课程设计/1.单周期FPGA/regfile.v
  C:/Users/lnsqr/Documents/GitHub/CPU_LAB/Lab5课程设计/1.单周期FPGA/controller.v
  C:/Users/lnsqr/Documents/GitHub/CPU_LAB/Lab5课程设计/1.单周期FPGA/ALU.v
  C:/Users/lnsqr/Documents/GitHub/CPU_LAB/Lab5课程设计/1.单周期FPGA/divider.v
  C:/Users/lnsqr/Documents/GitHub/CPU_LAB/Lab5课程设计/1.单周期FPGA/operating_parameter.v
  C:/Users/lnsqr/Documents/GitHub/CPU_LAB/Lab5课程设计/1.单周期FPGA/led.v
  C:/Users/lnsqr/Documents/GitHub/CPU_LAB/Lab5课程设计/1.单周期FPGA/pc.v
  C:/Users/lnsqr/Documents/GitHub/CPU_LAB/Lab5课程设计/1.单周期FPGA/display.v
  C:/Users/lnsqr/Documents/GitHub/CPU_LAB/Lab5课程设计/1.单周期FPGA/i7_6700k.v
}
read_xdc C:/Users/lnsqr/Documents/GitHub/CPU_LAB/Lab5课程设计/1.单周期FPGA/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/lnsqr/Documents/GitHub/CPU_LAB/Lab5课程设计/1.单周期FPGA/Nexys4DDR_Master.xdc]

synth_design -top i7_6700k -part xc7a100tcsg324-1
write_checkpoint -noxdef i7_6700k.dcp
catch { report_utilization -file i7_6700k_utilization_synth.rpt -pb i7_6700k_utilization_synth.pb }
