# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Administrator/Desktop/myi9/I9_7980XE/I9_7980XE.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator/Desktop/myi9/I9_7980XE/I9_7980XE.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Administrator/Desktop/i9/DEC.v
  C:/Users/Administrator/Desktop/i9/MUX.v
  C:/Users/Administrator/Desktop/i9/CONT.v
  C:/Users/Administrator/Desktop/i9/PC.v
  C:/Users/Administrator/Desktop/i9/LOAD.v
  C:/Users/Administrator/Desktop/i9/DIV.v
  C:/Users/Administrator/Desktop/i9/IF_ID.v
  C:/Users/Administrator/Desktop/i9/DISP.v
  C:/Users/Administrator/Desktop/i9/EX_MEM.v
  C:/Users/Administrator/Desktop/i9/HALT.v
  C:/Users/Administrator/Desktop/i9/JBUB.v
  C:/Users/Administrator/Desktop/i9/CACU.v
  C:/Users/Administrator/Desktop/i9/ID_EX.v
  C:/Users/Administrator/Desktop/i9/MEM_WB.v
  C:/Users/Administrator/Desktop/i9/DS.v
  C:/Users/Administrator/Desktop/i9/ALU.v
  C:/Users/Administrator/Desktop/i9/FORW.v
  C:/Users/Administrator/Desktop/i9/TYPEC.v
  C:/Users/Administrator/Desktop/i9/REGF.v
  C:/Users/Administrator/Desktop/i9/SHOW.v
  C:/Users/Administrator/Desktop/i9/IS.v
  C:/Users/Administrator/Desktop/i9/NPC.v
  C:/Users/Administrator/Desktop/i9/EXT.v
  C:/Users/Administrator/Desktop/i9/LED.v
  C:/Users/Administrator/Desktop/i9/i9_7980XE.v
}
read_xdc C:/Users/Administrator/Desktop/i9/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Administrator/Desktop/i9/Nexys4DDR_Master.xdc]

synth_design -top i9_7980XE -part xc7a100tcsg324-1
write_checkpoint -noxdef i9_7980XE.dcp
catch { report_utilization -file i9_7980XE_utilization_synth.rpt -pb i9_7980XE_utilization_synth.pb }
